### ISSUE TITLE
GraphicsOutput.RTMCopyRam can change the type of the texture

### ISSUE THREAD

**Issue by Clockwork-Muse** [panda3d/panda3d#1141]
## Description
When a render texture is added to a buffer and `GraphicsOutput.RTMCopyRam` is specified, the type of the texture may end up being changed after the frame is rendered.

Switching to `GraphicsOutput.RTMBindOrCopy` and extracting the texture with `graphicsEngine.extract_texture_data(...)` yields the expected texture data.

## Steps to Reproduce
```python
from direct.showbase.ShowBase import ShowBase
from panda3d.core import FrameBufferProperties, GraphicsOutput, GraphicsPipe, Texture, WindowProperties, loadPrcFileData

class MyApp(ShowBase):
    def __init__(self):
        super().__init__(self)

        props = FrameBufferProperties()
        props.set_rgba_bits(16, 0, 0, 0)
        props.set_float_color(False)

        wp = WindowProperties()
        wp.setSize(16, 16)

        flags = GraphicsPipe.BFRefuseWindow
        print(props)
        buffer = self.graphicsEngine.make_output(
            self.pipe, "int buffer", -1, props, wp, flags, self.win.get_gsg(), self.win)
        print(buffer.get_fb_properties())
        self.texture = Texture()
        buffer.add_render_texture(tex=self.texture, mode=GraphicsOutput.RTMCopyRam, bitplane=GraphicsOutput.RTPColor)
        print_texture_details(self.texture)

def print_texture_details(texture: Texture):
    print(f'Compressed: {texture.get_ram_image_compression()} {texture.get_ram_image_size()}, Format: {texture.get_format()}, Component Type: {texture.get_component_type()}, width: {texture.get_component_width()}, c: {texture.get_num_components()}')

def generate_synth():
    loadPrcFileData("",
    """
        window-type offscreen
        aux-display p3headlessgl
        win-size 1024 768
        model-cache-dir
    """)

    base = MyApp()

    base.graphicsEngine.render_frame()
    base.graphicsEngine.render_frame()
    base.graphicsEngine.render_frame()
    base.graphicsEngine.render_frame()

    # base.graphicsEngine.extract_texture_data(base.texture, base.win.get_gsg())

    print_texture_details(base.texture)


generate_synth()
```
Outputs: 
```text
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
:display:x11display(error): Could not open display ":1".
:display:egldisplay(warning): Couldn't initialize the default EGL display: EGL_NOT_INITIALIZED

< audio errors elided because uninteresting >

color_bits=16 red_bits=16 
color_bits=16 red_bits=16 force_hardware 
Compressed: 1 0, Format: 27, Component Type: 0, width: 1, c: 1
Compressed: 1 1536, Format: 7, Component Type: 1, width: 2, c: 3
```

Not only has the texture switched from R16 to RGB16, the component type has also switched from integer to float!  Which might yield even worse results.

## Environment
 * Operating system: Ubuntu 20.04
 * Docker Container base: nvidia/opengl:1.2-glvnd-runtime-ubuntu20.04
 * System architecture: x86_64
 * Panda3D version: 1.10.9
 * Installation method: built from source, commit ab4367ee7bf0fe11fec936e28ddc0f936a6548ff for 1.10.9
 * Python version: 3.8.5
 * Compiler (if using C++):

**Comment by rdb** [comment]
The copy-to-ram operation always re-setups the texture to match the current framebuffer configuration.  In this case it actually changed the component type to T_unsigned_short (not float), which is exactly what it is supposed to do.  It did change the format to F_rgb, but that's not a big issue because F_rgb maps to GL_RGB16 if the component type is T_unsigned_short.  Though, I suppose it is unfortunate that the format selection is not unambiguous here.

I do think there needs to be a clearer way to ask for an integer framebuffer (perhaps a `set_int_color` flag on FrameBufferProperties), but that discussion is for #1138.

Are you experiencing any issues from the current behaviour?

**Comment by Clockwork-Muse** [comment]
I haven't looked into whether there's any _render_ issues.

The problem is that I'm trying to avoid conversion or processing on the CPU - I just want to blit to a numpy buffer, and the current behavior would require me to strip the extra components.  
(Additional processing is anticipated to take more than one frame, which means I want to submit the data to another thread, so I want to release the borrow of the texture ram pointer)

**Comment by rdb** [comment]
You're getting T_unsigned_short, so there's no conversion happening.

**Comment by Clockwork-Muse** [comment]
Yes, but the texture ends up being 3x the size, and still requires me to strip the extra components.  For this particular example the buffer should only be 512 bytes, instead of 1536.

**Comment by rdb** [comment]
Sorry, I missed that you're getting 3 components instead of 1.  That I can fix.

**Comment by Clockwork-Muse** [comment]
Thanks!

**Comment by rdb** [comment]
Fixed, new wheels available at:
http://buildbot.panda3d.org/downloads/31feeb9b9fb9bad726c9c81910035a7310890d0a/

**Comment by Clockwork-Muse** [comment]
Yes, that seems to correct that.

(Now I have to figure out why my code is giving me open gl errors, but I don't think it's related)

**Comment by Clockwork-Muse** [comment]
@rdb - 
I'm running into this again with a different texture type, only this time not only is wrong after the copy to ram, but the intially-created buffer has the wrong type as well.

```python
from direct.showbase.ShowBase import ShowBase
from panda3d.core import FrameBufferProperties, GraphicsOutput, GraphicsPipe, Texture, WindowProperties, loadPrcFileData

class MyApp(ShowBase):
    def __init__(self):
        super().__init__(self)

        props = FrameBufferProperties()
        props.set_red_bits(32)
        props.set_float_color(False)

        wp = WindowProperties()
        wp.setSize(16, 16)

        flags = GraphicsPipe.BFRefuseWindow
        print(props)
        buffer = self.graphicsEngine.make_output(
            self.pipe, "int buffer", -1, props, wp, flags, self.win.get_gsg(), self.win)
        print(buffer.get_fb_properties())
        self.texture = Texture()
        buffer.add_render_texture(tex=self.texture, mode=GraphicsOutput.RTMCopyRam, bitplane=GraphicsOutput.RTPColor)
        print_texture_details(self.texture)

def print_texture_details(texture: Texture):
    print(
        f'Compressed: {Texture.format_compression_mode(texture.get_ram_image_compression())} {texture.get_ram_image_size()}, '
        f'Format: {Texture.format_format(texture.format)}, '
        f'Component Type: {Texture.format_component_type(texture.component_type)}, '
        f'width: {texture.component_width}, c: {texture.get_num_components()}'
    )

def generate_synth():
    loadPrcFileData("",
    """
        audio-library-name null
        window-type offscreen
        aux-display p3headlessgl
        win-size 1024 768
        model-cache-dir
    """)

    base = MyApp()

    base.graphicsEngine.render_frame()
    base.graphicsEngine.render_frame()
    base.graphicsEngine.render_frame()
    base.graphicsEngine.render_frame()

    # base.graphicsEngine.extract_texture_data(base.texture, base.win.get_gsg())

    print_texture_details(base.texture)


generate_synth()
```
... the buffer should be a 32-bit (signed) int buffer, but it instead prints out:
```shell
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
red_bits=32 
red_bits=32 
Compressed: off 0, Format: r32, Component Type: unsigned_byte, width: 1, c: 1
Compressed: off 512, Format: red, Component Type: unsigned_short, width: 2, c: 1
```
Since I can at least get a 32-bit float out I'm going to explore using that.
Given how the extract code is implemented, does it make more sense to deal with this completely once #1138 finally gets implemented?

**Comment by Clockwork-Muse** [comment]
Also, the original issue still repros for Windows.  I don't actually need it to work on Windows - my deployment environment is Linux - but thought I'd mention it nonetheless.

```shell
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
:display(warning): FrameBufferProperties available less than requested.
  requested: depth_bits=1 color_bits=3 red_bits=1 green_bits=1 blue_bits=1 alpha_bits=1 back_buffers=1 force_hardware
  got: depth_bits=24 color_bits=24 red_bits=8 green_bits=8 blue_bits=8 alpha_bits=8 accum_bits=64 force_hardware 
red_bits=16 
red_bits=16 
Compressed: off 0, Format: r16, Component Type: unsigned_byte, width: 1, c: 1
Compressed: off 768, Format: rgb, Component Type: unsigned_byte, width: 1, c: 3
```
