### ISSUE TITLE
MacOS: glgsg error when enabling msaa on floating point color buffer

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#756]
On MacOS, when activating MSAA on a frame buffer with floating point color the glgsg throws errors then abort because the configuration is not supported by the driver but not detected by Panda. This happens both with the legacy profile and the core profile.

Here is a minimal test program :

<pre>
#!/usr/bin/env python

import panda3d.core as p3d
from direct.showbase.ShowBase import ShowBase
from direct.filter.FilterManager import FilterManager

p3d.load_prc_file_data("", "gl-check-errors #t\n")
#p3d.load_prc_file_data("", "gl-version 3 2\n")

base = ShowBase()

manager = FilterManager(base.win, base.cam)
fbprops = p3d.FrameBufferProperties()
fbprops.float_color = True
fbprops.set_multisamples(4)
scene_tex = p3d.Texture()
tonemap_quad = manager.render_scene_into(colortex=scene_tex, fbprops=fbprops)

base.run()
</pre>

See forum thread : https://discourse.panda3d.org/t/gltf-viewer-glgsg-error-on-mac-when-using-msaa/25236

**Comment by rdb** [comment]
I'm getting some strong déjà vu:
https://discourse.panda3d.org/t/multisampling-srgb-and-intermediate-buffers/24304
https://github.com/panda3d/panda3d/commit/886d44d15d191c2b0bf1dea4ed15bce517fbc47d

What's different here, I guess, is that the buffer is 16-bit float, but the multisample buffer is being created as 32-bit float, so we need to add an extra case.

**Comment by el-dee** [comment]
You have a better memory than me :) And indeed, when setting explicitly the component size to 32 it works fine.

**Comment by rdb** [comment]
I think 6dcaab2d3ad6ee6f12b34622a13dddf28772e840 should fix it, would you mind testing it to be sure?

**Comment by el-dee** [comment]
Will an installer be available on buildbot ? (I tried building from source but the resulting sdk crashes at startup when instancing CocoaGraphicsPipe(). Actually it's the first time I compile Panda on Mojave...)

**Comment by rdb** [comment]
Give this a try:

**Comment by el-dee** [comment]
Thanks, it works fine with your build :)

I will look why I can't have a valid build with Mojave...

**Comment by duburcqa** [comment]
For the record, to this day it is still crashing with the following image format:
```
import panda3d.core as p3d
from direct.showbase.ShowBase import ShowBase
from direct.filter.FilterManager import FilterManager

p3d.load_prc_file_data("", "gl-check-errors #t\n")

base = ShowBase()
manager = FilterManager(base.win, base.cam)
fbprops = p3d.FrameBufferProperties()
fbprops.set_rgba_bits(8, 8, 8, 0). # 8, 8, 8, 8 is working fine
fbprops.set_multisamples(4)
scene_tex = p3d.Texture()
tonemap_quad = manager.render_scene_into(colortex=scene_tex, fbprops=fbprops)
base.run()
```
